name: Run API Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "17,42 * * * *"  # Runs at the 17th and 42nd minute of every hour

jobs:
  run-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        customer:
          - name: AKME
            env: prod
            secret_name: CUSTOMER_GUID_AKME
          - name: ARMO
            env: prod
            secret_name: CUSTOMER_GUID_ARMO
          - name: Billogram
            env: prod
            secret_name: CUSTOMER_GUID_BILLOGRAM
          - name: AXUAL
            env: prod
            secret_name: CUSTOMER_GUID_AXUAL
          - name: Kyos
            env: prod
            secret_name: CUSTOMER_GUID_KYOS
          - name: Schuberg_Philis
            env: prod
            secret_name: CUSTOMER_GUID_SCHUBERG_PHILIS
          - name: Mimecast
            env: prod
            secret_name: CUSTOMER_GUID_MIMECAST
          - name: BitDefender
            env: prod
            secret_name: CUSTOMER_GUID_BITDEFENDER
          - name: ARMO_EEE
            env: dev
            secret_name: CUSTOMER_GUID_ARMO_EEE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        timeout-minutes: 10
        with:
          python-version: 3.8
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_api.txt

      - name: Run API test for ${{ matrix.customer.name }}
        env:
          EMAIL: ${{ secrets.ST_EMAIL }}
          CUSTOMER: ${{ secrets.ST_CUSTOMER }}
          PASSWORD: ${{ secrets.ST_PASSWORD }}
          CUSTOMER_GUID: ${{ secrets[ matrix.customer.secret_name ] }}
        run: |
          python test_api.py --env ${{ matrix.customer.env }} --email $EMAIL --customer $CUSTOMER --password $PASSWORD --customer_guid $CUSTOMER_GUID --log_name ${{ matrix.customer.name }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update logs with new data for ${{ matrix.customer.name }}"
          author_name: bvolovat
          author_email: borisv@armosec.io
          commit: --signoff
          pull: '--ff-only'
          add: ./logs/api_test_log_${{ matrix.customer.name }}.csv
