name: Run Python Script in Parallel

on: 
  push:
    branches:
    - payment

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests in'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  jsonAccountDataPath: "./accountsData.json"


jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Generate matrix for account IDs
      id: set-matrix
      run: |
        echo "Reading account IDs from JSON for specified environment..."
        ACCOUNT_IDS=$(python fetch_account_ids.py --environment ${{ inputs.environment }} --jsonFile ${{ env.jsonAccountDataPath }})
        echo "# ----------------- ACCOUNT IDS----------------- #"
        echo "$ACCOUNT_IDS"
        echo "# ------------------------------------------------ #"
        echo "matrix=$ACCOUNT_IDS" >> $GITHUB_OUTPUT
        


  run_script:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: ${{fromJson(needs.setup_matrix.outputs.matrix)}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run script for each account ID
      run: |
        echo "Running script for account ID: ${{ matrix.account }}"
        python payment.py --account-id ${{ matrix.account }}


