name: sso login test

on:
  workflow_dispatch:
# Triggers the workflow every day at 13:00
  schedule:
  - cron: '0 13 * * *'
  # push:
  #   branches:
  #   - onboarding-check

jobs:
  run-sso-login-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Set up Python environment
          uses: actions/setup-python@v4
          timeout-minutes: 10
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: run-sso-login-test
          id: sso-login-test
          env:
            email_SSO: ${{ secrets.EMAIL_SSO }}
            login_pass_SSO: ${{ secrets.LOGIN_PASS_SSO }}
          run: |
            python sso_login.py --email ${{ env.email_SSO }} --password ${{ env.login_pass_SSO }}

        - name: better-up-time
          # if: failure()
          if: failure() && steps.sso-login-test.outcome == 'failure'
          run: |
            curl --request POST \
              --url https://uptime.betterstack.com/api/v3/incidents \
              --header "Authorization: Bearer ${{ secrets.BETTER_UPTIME_TOKEN }}" \
              --header 'Content-Type: application/json' \
              --data '{"name": "SSO login test failed! ","summary": "SSO login test failed on EU!","sms": "true", "email": "true", "call": "false", "requester_email": "borisv@armosec.io", "description": "SSO login test failed on EU! "}'  

        - name: upload screenshots
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: screenshots
            path: | 
              ./*.png