name: user-flow-tests

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to run the tests'
        options:
        - development
        - staging
        - production
        type: choice
        default: production
        required: true
      TEST_TYPE:
        description: 'Which test to run'
        options:
        - all
        - compliance
        - vulnerabilities
        type: choice
        default: all
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
      test_type: ${{ steps.set-test-type.outputs.test_type }}
    steps:
    - name: Step 1 - Print Trigger info
      run: |
        echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}"
        echo "TEST_TYPE=${{ inputs.TEST_TYPE }}"

    - name: Set environment output
      id: set-environment
      run: |
        echo "environment=${{ inputs.ENVIRONMENT }}" >> $GITHUB_OUTPUT
    
    - name: Set test type output
      id: set-test-type
      run: |
        echo "test_type=${{ inputs.TEST_TYPE }}" >> $GITHUB_OUTPUT

  test_vulnerabilities:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'vulnerabilities'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.TEST_EMAIL_VULNERABILITIES }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD_VULNERABILITIES }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      timeout-minutes: 10
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Vulnerabilities Test
      run: |
        python main.py ${{ env.ENVIRONMENT }} vulnerabilities $TEST_EMAIL $TEST_PASSWORD

  test_compliance:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'compliance'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.TEST_EMAIL_COMPLIANCE }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD_COMPLIANCE }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      timeout-minutes: 10
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Compliance Test
      run: |
        python main.py ${{ env.ENVIRONMENT }} compliance $TEST_EMAIL $TEST_PASSWORD
