name: user-flow-tests-1cluster
# this workflow is for testing the user flow on a single cluster

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to run the tests'
        options:
        - predev
        # - dev
        # - staging
        - production
        type: choice
        default: production
        required: true
      TEST_TYPE:
        description: 'Which test to run'
        options:
        - all
        - compliance
        - vulnerabilities
        - attach-path
        - security-risk
        - settings
        type: choice
        default: all
        required: true
  schedule:
    - cron: "0 */2 * * *" # every 2 hours (UTC)

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
      test_type: ${{ steps.set-test-type.outputs.test_type }}
    steps:
    - name: Print trigger info (resolved)
      run: |
        echo "EVENT=${{ github.event_name }}"
        echo "Resolved ENVIRONMENT=${{ inputs.ENVIRONMENT || 'production' }}"
        echo "Resolved TEST_TYPE=${{ inputs.TEST_TYPE || 'all' }}"

    - name: Set environment output
      id: set-environment
      run: |
        echo "environment=${{ inputs.ENVIRONMENT || 'production' }}" >> $GITHUB_OUTPUT

    - name: Set test type output
      id: set-test-type
      run: |
        echo "test_type=${{ inputs.TEST_TYPE || 'all' }}" >> $GITHUB_OUTPUT

  test_vulnerabilities:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'vulnerabilities'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.COMMON_EMAIL }}
      TEST_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Vulnerabilities Test
      run: |
        python main.py "${{ env.ENVIRONMENT }}" vulnerabilities "${{ env.TEST_EMAIL }}" "${{ env.TEST_PASSWORD }}" false

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-vulnerabilities
        path: |
          ./*.png

  test_compliance:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'compliance'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.COMMON_EMAIL }}
      TEST_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Compliance Test
      run: |
        python main.py "${{ env.ENVIRONMENT }}" compliance "${{ env.TEST_EMAIL }}" "${{ env.TEST_PASSWORD }}" false

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-compliance
        path: |
          ./*.png

  test_attach_path:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'attach-path'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.COMMON_EMAIL }}
      TEST_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Attach Path Test
      run: |
        python main.py "${{ env.ENVIRONMENT }}" attach-path "${{ env.TEST_EMAIL }}" "${{ env.TEST_PASSWORD }}" false

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-attach-path
        path: |
          ./*.png

  test_security_risk:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'security-risk'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.COMMON_EMAIL }}
      TEST_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Security Risk Test
      run: |
        python main.py "${{ env.ENVIRONMENT }}" security-risk "${{ env.TEST_EMAIL }}" "${{ env.TEST_PASSWORD }}" false

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-security-risk
        path: |
          ./*.png

  test_settings:
    needs: setup
    if: needs.setup.outputs.test_type == 'all' || needs.setup.outputs.test_type == 'settings'
    runs-on: ubuntu-latest
    env:
      TEST_EMAIL: ${{ secrets.COMMON_EMAIL }}
      TEST_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Settings Test
      run: |
        python main.py "${{ env.ENVIRONMENT }}" settings "${{ env.TEST_EMAIL }}" "${{ env.TEST_PASSWORD }}" false

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-settings
        path: |
          ./*.png